fontsize: '28-31'
fontsize_set: [28, 29, 30, 31, 32, 34, 33, 44, 48, 52, 64]
font_path: 'assets/vnm_fonts'
words: 'assets/corpus/test.txt'
period_prob: 0.15
prob_image: 0.3
prob_table: 0.15
bg_img: 'assets/bg'
img_height: 2000
img_width: 1500
col_spacing: '40-50'
space_between: True

background_path: '../resources_1/bg_img'
plot_path: 'assets/all_plot'
formula_path: 'assets/formula'
type: 'page'
col_range: '1-3'

col_spacing: '35-50'
spacing: 0.2
visible_column_prob: 0.4

tab_at_start: True
blur: True
vis_line: False
vis_word: False
vis_char: False
vis_cell: False

repeat: 20000
print_freq: 100
